AI_CHANNELS_POOL = [
    {"name": "Tina Huang", "channel_id": "UC2UXDak6o7rBm23k3Vv5dww", "url": "https://www.youtube.com/channel/UC2UXDak6o7rBm23k3Vv5dww/videos"},
    {"name": "Kingy AI", "channel_id": "UC51g2r_bWOQq-7Y-VwU9sYA", "url": "https://www.youtube.com/channel/UC51g2r_bWOQq-7Y-VwU9sYA/videos"},
    {"name": "AI Revolution", "channel_id": "UC5l7RouTQ60oUjLjt1Nh-UQ", "url": "https://www.youtube.com/channel/UC5l7RouTQ60oUjLjt1Nh-UQ/videos"},
    {"name": "TheAIGRID", "channel_id": "UCbY9xX3_jW5c2fjlZVBI4cg", "url": "https://www.youtube.com/channel/UCbY9xX3_jW5c2fjlZVBI4cg/videos"},
    {"name": "AI Engineer", "channel_id": "UCLKPca3kwwd-B59HNr-_lvA", "url": "https://www.youtube.com/channel/UCLKPca3kwwd-B59HNr-_lvA/videos"},
    {"name": "Neural Nutshell", "channel_id": "UCE0-acFJdnTPUCYlYoiq_fg", "url": "https://www.youtube.com/channel/UCE0-acFJdnTPUCYlYoiq_fg/videos"},
    {"name": "AI Master", "channel_id": "UC0yHbz4OxdQFwmVX2BBQqLg", "url": "https://www.youtube.com/channel/UC0yHbz4OxdQFwmVX2BBQqLg/videos"},
    {"name": "WorldofAI", "channel_id": "UC2WmuBuFq6gL08QYG-JjXKw", "url": "https://www.youtube.com/channel/UC2WmuBuFq6gL08QYG-JjXKw/videos"},
    {"name": "IBM Technology", "channel_id": "UCKWaEZ-_VweaEx1j62do_vQ", "url": "https://www.youtube.com/channel/UCKWaEZ-_VweaEx1j62do_vQ/videos"},
    {"name": "AI Search", "channel_id": "UCIgnGlGkVRhd4qNFcEwLL4A", "url": "https://www.youtube.com/channel/UCIgnGlGkVRhd4qNFcEwLL4A/videos"},
    {"name": "Futurepedia", "channel_id": "UC_RovKmk0OCbuZjA8f08opw", "url": "https://www.youtube.com/channel/UC_RovKmk0OCbuZjA8f08opw/videos"},
    {"name": "Peter H. Diamandis", "channel_id": "UCvxm0qTrGN_1LMYgUaftWyQ", "url": "https://www.youtube.com/channel/UCvxm0qTrGN_1LMYgUaftWyQ/videos"},
    {"name": "Sabrina Ramonov", "channel_id": "UCiGWNa6QK6CiKPvv5-YPv8g", "url": "https://www.youtube.com/channel/UCiGWNa6QK6CiKPvv5-YPv8g/videos"},
    {"name": "Julia McCoy", "channel_id": "UCqzK60-oUOEq36uU9B1MMUg", "url": "https://www.youtube.com/channel/UCqzK60-oUOEq36uU9B1MMUg/videos"},
    {"name": "Bijan Bowen", "channel_id": "UCOCahKBCEUuzDJawM7yN1dg", "url": "https://www.youtube.com/channel/UCOCahKBCEUuzDJawM7yN1dg/videos"},
    {"name": "Doom Debates", "channel_id": "UCote8RH_wwSLza2Qb0GAQJw", "url": "https://www.youtube.com/channel/UCote8RH_wwSLza2Qb0GAQJw/videos"},
    {"name": "Wes Roth", "channel_id": "UCqcbQf6yw5KzRoDDcZ_wBSw", "url": "https://www.youtube.com/channel/UCqcbQf6yw5KzRoDDcZ_wBSw/videos"},
    {"name": "Vaibhav Sisinty", "channel_id": "UClXAalunTPaX1YV185DWUeg", "url": "https://www.youtube.com/channel/UClXAalunTPaX1YV185DWUeg/videos"},
    {"name": "Hamel Husain", "channel_id": "UC__dUuqF5w4OnbW221JxmKg", "url": "https://www.youtube.com/channel/UC__dUuqF5w4OnbW221JxmKg/videos"},
    {"name": "The AI Daily Brief: Artificial Intelligence News", "channel_id": "UCKelCK4ZaO6HeEI1KQjqzWA", "url": "https://www.youtube.com/channel/UCKelCK4ZaO6HeEI1KQjqzWA/videos"},
    {"name": "OpenAI", "channel_id": "UCXZCJLdBC09xxGZ6gcdrc6A", "url": "https://www.youtube.com/channel/UCXZCJLdBC09xxGZ6gcdrc6A/videos"},
    {"name": "Scale AI", "channel_id": "UCAHS4cP-uIXdrpCsSfGq_OA", "url": "https://www.youtube.com/channel/UCAHS4cP-uIXdrpCsSfGq_OA/videos"},
    {"name": "The Verge", "channel_id": "UCddiUEpeqJcYeBxX1IVBKvQ", "url": "https://www.youtube.com/channel/UCddiUEpeqJcYeBxX1IVBKvQ/videos"},
    {"name": "AI Foundations", "channel_id": "UCWZwfV3ICOt3uEPpW6hYK4g", "url": "https://www.youtube.com/channel/UCWZwfV3ICOt3uEPpW6hYK4g/videos"},
    {"name": "Stanford Online", "channel_id": "UCBa5G_ESCn8Yd4vw5U-gIcg", "url": "https://www.youtube.com/channel/UCBa5G_ESCn8Yd4vw5U-gIcg/videos"},
    {"name": "The AI Advantage", "channel_id": "UCHhYXsLBEVVnbvsq57n1MTQ", "url": "https://www.youtube.com/channel/UCHhYXsLBEVVnbvsq57n1MTQ/videos"},
    {"name": "Alex Finn", "channel_id": "UCfQNB91qRP_5ILeu_S_bSkg", "url": "https://www.youtube.com/channel/UCfQNB91qRP_5ILeu_S_bSkg/videos"},
    {"name": "LangChain", "channel_id": "UCC-lyoTfSrcJzA1ab3APAgw", "url": "https://www.youtube.com/channel/UCC-lyoTfSrcJzA1ab3APAgw/videos"},
    {"name": "AI With TechZnap", "channel_id": "UCNFrPN8weVeh4vUM3vCuS5Q", "url": "https://www.youtube.com/channel/UCNFrPN8weVeh4vUM3vCuS5Q/videos"},
    {"name": "Matt Pocock", "channel_id": "UCswG6FSbgZjbWtdf_hMLaow", "url": "https://www.youtube.com/channel/UCswG6FSbgZjbWtdf_hMLaow/videos"},
    {"name": "DeepLearningAI", "channel_id": "UCcIXc5mJsHVYTZR1maL5l9w", "url": "https://www.youtube.com/channel/UCcIXc5mJsHVYTZR1maL5l9w/videos"},
    {"name": "Riley Brown", "channel_id": "UCMcoud_ZW7cfxeIugBflSBw", "url": "https://www.youtube.com/channel/UCMcoud_ZW7cfxeIugBflSBw/videos"},
    {"name": "AI Jason", "channel_id": "UCrXSVX9a1mj8l0CMLwKgMVw", "url": "https://www.youtube.com/channel/UCrXSVX9a1mj8l0CMLwKgMVw/videos"},
    {"name": "freeCodeCamp.org", "channel_id": "UC8butISFwT-Wl7EV0hUK0BQ", "url": "https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ/videos"},
    {"name": "Parker Prompts", "channel_id": "UCaNk22cLid93kifuVbVapcQ", "url": "https://www.youtube.com/channel/UCaNk22cLid93kifuVbVapcQ/videos"},
    {"name": "David Ondrej", "channel_id": "UCPGrgwfbkjTIgPoOh2q1BAg", "url": "https://www.youtube.com/channel/UCPGrgwfbkjTIgPoOh2q1BAg/videos"},
    {"name": "Google Cloud Tech", "channel_id": "UCJS9pqu9BzkAMNTmzNMNhvg", "url": "https://www.youtube.com/channel/UCJS9pqu9BzkAMNTmzNMNhvg/videos"},
    {"name": "Aishwarya Srinivasan", "channel_id": "UCzd4ZN716evEjtbJERBMTfg", "url": "https://www.youtube.com/channel/UCzd4ZN716evEjtbJERBMTfg/videos"},
    {"name": "Matt Wolfe", "channel_id": "UChpleBmo18P08aKCIgti38g", "url": "https://www.youtube.com/channel/UChpleBmo18P08aKCIgti38g/videos"},
    {"name": "AI Explained", "channel_id": "UCNJ1Ymd5yFuUPtn21xtRbbw", "url": "https://www.youtube.com/channel/UCNJ1Ymd5yFuUPtn21xtRbbw/videos"},
    {"name": "All About AI", "channel_id": "UCR9j1jqqB5Rse69wjUnbYwA", "url": "https://www.youtube.com/channel/UCR9j1jqqB5Rse69wjUnbYwA/videos"},
    {"name": "David Shapiro", "channel_id": "UCvKRFNawVcuz4b9ihUTApCg", "url": "https://www.youtube.com/channel/UCvKRFNawVcuz4b9ihUTApCg/videos"},
    {"name": "Matthew Berman", "channel_id": "UCawZsQWqfGSbCI5yjkdVkTA", "url": "https://www.youtube.com/channel/UCawZsQWqfGSbCI5yjkdVkTA/videos"},
    {"name": "1littlecoder", "channel_id": "UCpV_X0VrL8-jg3t6wYGS-1g", "url": "https://www.youtube.com/channel/UCpV_X0VrL8-jg3t6wYGS-1g/videos"},
    {"name": "bycloud", "channel_id": "UCgfe2ooZD3VJPB6aJAnuQng", "url": "https://www.youtube.com/channel/UCgfe2ooZD3VJPB6aJAnuQng/videos"},
    {"name": "AI Uncovered", "channel_id": "UCUTF61UNExRdjmoK5mXwWfQ", "url": "https://www.youtube.com/channel/UCUTF61UNExRdjmoK5mXwWfQ/videos"},
    {"name": "Two Minute Papers", "channel_id": "UCbfYPyITQ-7l4upoX8nvctg", "url": "https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg/videos"},
    {"name": "Prompt Engineering", "channel_id": "UCDq7SjbgRKty5TgGafW8Clg", "url": "https://www.youtube.com/channel/UCDq7SjbgRKty5TgGafW8Clg/videos"},
    {"name": "TheAI Breakdown", "channel_id": "UCo87FcXozPDR3K7qT1QTLDA", "url": "https://www.youtube.com/channel/UCo87FcXozPDR3K7qT1QTLDA/videos"},
    {"name": "This Day in AI Podcast", "channel_id": "UCwpNW6o_Kc13HQY5ol4rzsw", "url": "https://www.youtube.com/channel/UCwpNW6o_Kc13HQY5ol4rzsw/videos"},
    {"name": "AI News & Strategy Daily | Nate B Jones", "channel_id": "UC0C-17n9iuUQPylguM1d-lQ", "url": "https://www.youtube.com/channel/UC0C-17n9iuUQPylguM1d-lQ/videos"},
    {"name": "Skill Leap AI", "channel_id": "UCwSozl89jl2zUDzQ4jGJD3g", "url": "https://www.youtube.com/channel/UCwSozl89jl2zUDzQ4jGJD3g/videos"},
    {"name": "AI Andy", "channel_id": "UCn2RJFAA1ndipnVJsYAwWOw", "url": "https://www.youtube.com/channel/UCn2RJFAA1ndipnVJsYAwWOw/videos"},
    {"name": "The Cognitive Revolution", "channel_id": "UCjNRVMBVI30Sak_p6HRWhIA", "url": "https://www.youtube.com/channel/UCjNRVMBVI30Sak_p6HRWhIA/videos"},
    {"name": "Julian Goldie SEO", "channel_id": "UCGpsgNbzdF7BECCVbB1COHw", "url": "https://www.youtube.com/channel/UCGpsgNbzdF7BECCVbB1COHw/videos"},
    {"name": "Ava Does AI", "channel_id": "UCeKNYDvbHFQS7fA38GpoR-g", "url": "https://www.youtube.com/channel/UCeKNYDvbHFQS7fA38GpoR-g/videos"},
    {"name": "Liam Ottley", "channel_id": "UCui4jxDaMb53Gdh-AZUTPAg", "url": "https://www.youtube.com/channel/UCui4jxDaMb53Gdh-AZUTPAg/videos"},
    {"name": "Income stream surfers", "channel_id": "UCctL30i8tVgSS9A37Q532eg", "url": "https://www.youtube.com/channel/UCctL30i8tVgSS9A37Q532eg/videos"},
    {"name": "Jason West", "channel_id": "UCctL30i8tVgSS9A37Q532eg", "url": "https://www.youtube.com/channel/UCctL30i8tVgSS9A37Q532eg/videos"},
    {"name": "Nate Herk | AI Automation", "channel_id": "UC2ojq-nuP8ceeHqiroeKhBA", "url": "https://www.youtube.com/channel/UC2ojq-nuP8ceeHqiroeKhBA/videos"},
    {"name": "Charlie Chang", "channel_id": "UCTQuKo8v0PaPCvk5aRxc_Yg", "url": "https://www.youtube.com/channel/UCTQuKo8v0PaPCvk5aRxc_Yg/videos"},
    {"name": "The Futur", "channel_id": "UC-b3c7kxa5vU-bnmaROgvog", "url": "https://www.youtube.com/channel/UC-b3c7kxa5vU-bnmaROgvog/videos"},
    {"name": "Andrej Karpathy", "channel_id": "UCXUPKJO5MZQN11PqgIvyuvQ", "url": "https://www.youtube.com/channel/UCXUPKJO5MZQN11PqgIvyuvQ/videos"},
    {"name": "sentdex", "channel_id": "UCfzlCWGWYyIQ0aLC5w48gBQ", "url": "https://www.youtube.com/channel/UCfzlCWGWYyIQ0aLC5w48gBQ/videos"},
    {"name": "StatQuest with Josh Starmer", "channel_id": "UCtYLUTtgS3k1Fg4y5tAhLbw", "url": "https://www.youtube.com/channel/UCtYLUTtgS3k1Fg4y5tAhLbw/videos"},
    {"name": "3Blue1Brown", "channel_id": "UCYO_jab_esuFRV4b17AJtAw", "url": "https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw/videos"},
    {"name": "AI Coffee Break with Letitia", "channel_id": "UCobqgqE4i5Kf7wrxRxhToQA", "url": "https://www.youtube.com/channel/UCobqgqE4i5Kf7wrxRxhToQA/videos"},
    {"name": "Machine Learning Street Talk", "channel_id": "UCMLtBahI5DMrt0NPvDSoIRQ", "url": "https://www.youtube.com/channel/UCMLtBahI5DMrt0NPvDSoIRQ/videos"},
    {"name": "CodeEmporium", "channel_id": "UC5_6ZD6s8klmMu9TXEB_1IA", "url": "https://www.youtube.com/channel/UC5_6ZD6s8klmMu9TXEB_1IA/videos"},
    {"name": "Aleksa Gordić - The AI Epiphany", "channel_id": "UCj8shE7aIn4Yawwbo2FceCQ", "url": "https://www.youtube.com/channel/UCj8shE7aIn4Yawwbo2FceCQ/videos"},
    {"name": "AssemblyAI", "channel_id": "UCtatfZMf-8EkIwASXM4ts0A", "url": "https://www.youtube.com/channel/UCtatfZMf-8EkIwASXM4ts0A/videos"},
    {"name": "Cole Medin", "channel_id": "UCMwVTLZIRRUyyVrkjDpn4pA", "url": "https://www.youtube.com/channel/UCMwVTLZIRRUyyVrkjDpn4pA/videos"},
    {"name": "Mervin Praison", "channel_id": "UCWTyktbw5JYoSBduu8LsBgQ", "url": "https://www.youtube.com/channel/UCWTyktbw5JYoSBduu8LsBgQ/videos"},
    {"name": "Nicholas Renotte", "channel_id": "UCHXa4OpASJEwrHrLeIzw7Yg", "url": "https://www.youtube.com/channel/UCHXa4OpASJEwrHrLeIzw7Yg/videos"},
    {"name": "Krish Naik", "channel_id": "UCNU_lfiiWBdtULKOw6X0Dig", "url": "https://www.youtube.com/channel/UCNU_lfiiWBdtULKOw6X0Dig/videos"},
    {"name": "Data Science Dojo", "channel_id": "UCzL_0nIe8B4-7ShhVPfJkgw", "url": "https://www.youtube.com/channel/UCzL_0nIe8B4-7ShhVPfJkgw/videos"},
    {"name": "Tech With Tim", "channel_id": "UC4JX40jDee_tINbkjycV4Sg", "url": "https://www.youtube.com/channel/UC4JX40jDee_tINbkjycV4Sg/videos"},
    {"name": "codebasics", "channel_id": "UCh9nVJoWXmFb7sLApWGcLPQ", "url": "https://www.youtube.com/channel/UCh9nVJoWXmFb7sLApWGcLPQ/videos"},
    {"name": "Jeremy Howard / fast.ai", "channel_id": "UCX7Y2qWriXpqocG97SFW2OQ", "url": "https://www.youtube.com/channel/UCX7Y2qWriXpqocG97SFW2OQ/videos"},
    {"name": "Rob Mulla", "channel_id": "UCxladMszXan-jfgzyeIMyvw", "url": "https://www.youtube.com/channel/UCxladMszXan-jfgzyeIMyvw/videos"},
    {"name": "Edureka", "channel_id": "UCkw4JCwteGrDHIsyIIKo4tQ", "url": "https://www.youtube.com/channel/UCkw4JCwteGrDHIsyIIKo4tQ/videos"},
    {"name": "Simplilearn", "channel_id": "UCsvqVGtbbyHaMoevxPAq9Fg", "url": "https://www.youtube.com/channel/UCsvqVGtbbyHaMoevxPAq9Fg/videos"},
    {"name": "Great Learning", "channel_id": "UCObs0kLIrDjX2LLSybqNaEA", "url": "https://www.youtube.com/channel/UCObs0kLIrDjX2LLSybqNaEA/videos"},
    {"name": "Corey Schafer", "channel_id": "UCCezIgC97PvUuR4_gbFUs5g", "url": "https://www.youtube.com/channel/UCCezIgC97PvUuR4_gbFUs5g/videos"},
    {"name": "MIT OpenCourseWare", "channel_id": "UCFe-pfe0a9bDvWy74Jd7vFg", "url": "https://www.youtube.com/channel/UCFe-pfe0a9bDvWy74Jd7vFg/videos"},
    {"name": "Lex Fridman", "channel_id": "UCSHZKyawb77ixDdsGog4iWA", "url": "https://www.youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA/videos"},
    {"name": "Dwarkesh Patel", "channel_id": "UCXl4i9dYBrFOabk0xGmbkRA", "url": "https://www.youtube.com/channel/UCXl4i9dYBrFOabk0xGmbkRA/videos"},
    {"name": "No Priors", "channel_id": "UCSI7h9hydQ40K5MJHnCrQvw", "url": "https://www.youtube.com/channel/UCSI7h9hydQ40K5MJHnCrQvw/videos"},
    {"name": "The TWIML AI Podcast", "channel_id": "UC7kjWIK1H8tfmFlzZO-wHMw", "url": "https://www.youtube.com/channel/UC7kjWIK1H8tfmFlzZO-wHMw/videos"},
    {"name": "Latent Space", "channel_id": "UCxBcwypKK-W3GHd_RZ9FZrQ", "url": "https://www.youtube.com/channel/UCxBcwypKK-W3GHd_RZ9FZrQ/videos"},
    {"name": "a16z", "channel_id": "UC9cn0TuPq4dnbTY-CBsm8XA", "url": "https://www.youtube.com/channel/UC9cn0TuPq4dnbTY-CBsm8XA/videos"},
    {"name": "Julian Goldie Podcast", "channel_id": "UCgl54MMemaGR47QeWs-lRcQ", "url": "https://www.youtube.com/channel/UCgl54MMemaGR47QeWs-lRcQ/videos"},
    {"name": "Google DeepMind", "channel_id": "UCP7jMXSY2xbc3KCAE0MHQ-A", "url": "https://www.youtube.com/channel/UCP7jMXSY2xbc3KCAE0MHQ-A/videos"}
]